name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug repository structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
            pip install pytest
            python -m pip install --upgrade pip
            pip install pytest
    #       pip install -r requirements.txt

      - name: Debug pytest installation
        run: |
            pip show pytest

      - name: Run tests
        run: |
          pytest tests/